# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - main
  paths:
    include:
      - .ci/ros/azure-pipelines.yml
      - docker/ros_preception/Dockerfile

pr:
  paths:
    include:
      - .ci/ros/azure-pipelines.yml
      - docker/ros_preception/Dockerfile

schedules:
- cron: "0 0 * * 0"
  displayName: "Sunday midnight build"
  branches:
    include:
    - main

resources:
- repo: self

variables:
  dockerHub: 'Docker Hub'
  dockerHubID: 'prachandabhanu'

jobs:
- job: BuildAndPush
  displayName: "Env"
  pool:
    vmImage: 'ubuntu-latest'
  strategy:
    matrix:
      Ubuntu 18.04:
        ROS_DISTRO: melodic
        tag: $(ROS_DISTRO)-perception
      Ubuntu 20.4:
        ROS_DISTRO: noetic
        tag: $(ROS_DISTRO)-perception
  steps:
  - task: Docker@2
    displayName: "Build Docker Image"
    inputs:
      command: build
      arguments: |
        --no-cache
        --build-arg ROS_DISTRO=$(ROS_DISTRO)
        -t $(dockerHubID)/env:$(tag)
      Dockerfile: '$(Build.SourcesDirectory)/docker/ros_perception/Dockerfile'
      tags: "$(tag)"
  
  - task: Docker@2
    inputs:
      command: 'push'
      containerRegistry: $(dockerHub)
      repository: $(dockerHubID)/env
      tags: "$(tag)"